<a href="https://colab.research.google.com/github/ShrutiChrist/Computer-Vision/blob/main/ExtraProgram2_2348545(CV).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sampling: Sampling is the process of converting a continuous signal into a discrete signal. This involves selecting specific points (samples) from the continuous signal at regular intervals. The rate at which samples are taken is known as the sampling rate.

Quantization: Quantization is the process of converting the amplitude of each sample into a finite set of values. In other words, it involves approximating the continuous amplitude values with a limited number of discrete levels.

In [1]:
import numpy as np
from scipy import ndimage

# Create a sample continuous signal (e.g., a 2D image)
continuous_signal = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])

# Define the sampling rate
sampling_rate = 2

# Perform sampling to obtain a discrete signal
discrete_signal = continuous_signal[::sampling_rate, ::sampling_rate]

# Apply quantization by reducing the number of amplitude levels
quantized_signal = np.round(discrete_signal / 2) * 2  # For example, quantizing to even numbers

# Apply interpolation techniques
bilinear_interpolated_signal = ndimage.zoom(quantized_signal, 2, order=1)  # Bilinear interpolation
bicubic_interpolated_signal = ndimage.zoom(quantized_signal, 2, order=3)  # Bicubic interpolation
nearest_neighbor_interpolated_signal = ndimage.zoom(quantized_signal, 2, order=0)  # Nearest neighbor interpolation

# Print the results
print("Original Signal:\n", continuous_signal)
print("\nDiscrete Signal (After Sampling):\n", discrete_signal)
print("\nQuantized Signal:\n", quantized_signal)
print("\nBilinear Interpolated Signal:\n", bilinear_interpolated_signal)
print("\nBicubic Interpolated Signal:\n", bicubic_interpolated_signal)
print("\nNearest Neighbor Interpolated Signal:\n", nearest_neighbor_interpolated_signal)


Original Signal:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Discrete Signal (After Sampling):
 [[1 3]
 [7 9]]

Quantized Signal:
 [[0. 4.]
 [8. 8.]]

Bilinear Interpolated Signal:
 [[0.         1.33333333 2.66666667 4.        ]
 [2.66666667 3.55555556 4.44444444 5.33333333]
 [5.33333333 5.77777778 6.22222222 6.66666667]
 [8.         8.         8.         8.        ]]

Bicubic Interpolated Signal:
 [[-1.58206781e-15  1.03703704e+00  2.96296296e+00  4.00000000e+00]
 [ 2.07407407e+00  2.84224966e+00  4.26886145e+00  5.03703704e+00]
 [ 5.92592593e+00  6.19478738e+00  6.69410151e+00  6.96296296e+00]
 [ 8.00000000e+00  8.00000000e+00  8.00000000e+00  8.00000000e+00]]

Nearest Neighbor Interpolated Signal:
 [[0. 0. 4. 4.]
 [0. 0. 4. 4.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
